version: 2
log-file: /tmp/efm.log
log-level: 1
root-markers:
  - .git/

tools:
  python-flake8: &python-flake8
    lint-command: 'flake8 --ignore=E501 --stdin-display-name ${INPUT} -'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  python-mypy: &python-mypy
    lint-command: 'mypy --ignore-missing-imports --disallow-untyped-defs'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  python-black: &python-black
    format-command: 'black -'
    format-stdin: true

  python-isort: &python-isort
    format-command: 'isort --profile black -'
    format-stdin: true

  python-yapf: &python-yapf
    format-command: 'yapf --quiet'
    format-stdin: true

  vue-eslint: &vue-eslint
    lint-command: './node_modules/.bin/eslint -f unix --stdin --stdin-filename ${INPUT}'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
    format-command: './node_modules/.bin/eslint --fix-to-stdout --stdin --stdin-filename=${INPUT}'
    format-stdin: true

  vue-prettier: &vue-prettier
    format-command: './node_modules/.bin/prettier --stdin-filepath ${INPUT}'
    format-stdin: true

  html-prettier: &html-prettier
    format-command: './node_modules/.bin/prettier --parser html --stdin-filepath ${INPUT}'

  json-prettier: &json-prettier
    format-command: './node_modules/.bin/prettier ${--tab-width:tabWidth} --parser json'

  json-jq: &json-jq
    lint-command: 'jq .'

  json-fixjson: &json-fixjson
    format-command: 'fixjson'

  yaml-yamllint: &yaml-yamllint
    lint-command: '/usr/local/bin/yamllint -f parsable -'
    lint-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint'
    lint-formats:
      - '%f:%l %m'

languages:
  python:
    - <<: *python-flake8
    - <<: *python-isort
    - <<: *python-black
  vue:
    - <<: *vue-prettier
  html:
    - <<: *html-prettier
  json:
    - <<: *json-jq
    - <<: *json-fixjson
  yaml:
    - <<: *yaml-yamllint
  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt
  dockerfile:
    - <<: *dockerfile-hadolint
